apiVersion: apps/v1
kind: Deployment
metadata:
  name: nato-container
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nato
  template:
    metadata:
      labels:
        app: nato
    spec:
      containers:
        - name: nato
          image: zboromir/nato:v3
