---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
- name: Initial config for deployed VM
  gather_facts: true
  become: true
  # Hosts: where our play will run and options it will run with
  hosts: all
  # Vars: variables that will apply to the play, on all target systems

  # Tasks: the list of tasks that will be executed within the play, this section
  #       can also be used for pre and post tasks
  tasks:
    - name: Patching
      apt:
        update_cache: true
        upgrade: dist
        autoremove: true
      notify: AptUpgrade

    - name: Setup Docker repository
      shell: |
        apt install -y ca-certificates curl
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        chmod a+r /etc/apt/keyrings/docker.asc
        
        tee /etc/apt/sources.list.d/docker.sources <<EOF
        Types: deb
        URIs: https://download.docker.com/linux/ubuntu
        Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
        Components: stable
        Signed-By: /etc/apt/keyrings/docker.asc
        EOF
        apt update
      notify: SetupDockerRepo
        
    - name: Install Docker  
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      notify: DockerInstall

    - name: Start docker
      service: 
        name: docker
        state: started
        enabled: true
      notify: DockerStart

    - name: Install MiniKube
      shell: |
        curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
      notify: InstallMiniKube
      
    - name: Start MiniKube
      shell: |
        sudo minikube start --driver=docker --force
      notify: StartMiniKube   

    - name: Install kubectl
      command: >
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      args:
        creates: /usr/local/bin/kubectl
      notify: InstallKubectl

    - name: Install kubectl binary
      copy:
        src: kubectl
        dest: /usr/local/bin/kubectl
        mode: "0755"
      notify: ConfigKubectl

    - name: Deploy NATO app
      kubernetes.core.k8s:
        kubeconfig: "/root/.kube/config"
        state: present
        src: "{{ item }}"
      loop: "{{ lookup('fileglob', '../k8s/*.yaml', wantlist=True) }}"
      notify: DeployApp 

      
#    - name: Start container
#      community.docker.docker_container:
#        name: nato-container
#        image: zboromir/nato:v3
#        published_ports: 
#          - "80:80"
#        cleanup: true
#        detach: true
#      notify: ContrainerStart
        
        
    
  # Handlers: the list of handlers that are executed as a notify key from a task
  handlers:
    - name: AptUpgrade
      debug:
        msg: "Patching completed"

    - name: SetupDockerRepo
      debug:
        msg: "Docker Repo setup"
        
    - name: DockerInstall
      debug:
        msg: "Docker installed"       
        
    - name: DockerStart
      debug:
        msg: "Docker Started"  

    - name: ContrainerStart
      debug:
        msg: "Contrainer Started"  
 
    - name: InstallMiniKube
      debug:
        msg: "Minikube Installed"  
        
    - name: StartMiniKube 
      debug:
        msg: "Minikube Started"  
    
    - name: InstallKubectl
      debug:
        msg: "Kubectl installed"  
        
    - name: ConfigKubectl 
      debug:
        msg: "Kubectl configured"  
        
    - name: DeployApp 
      debug:
        msg: "App Deployed"  
  # Roles: list of roles to be imported into the play

# Three dots indicate the end of a YAML document
...
