name: "Ansible Config"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed
 
jobs:
  Ansible:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Configure new EC2 instance"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ./ansible
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
       
      - name: Download Public IP from artifacts
        uses: actions/download-artifact@v4
        with:
          name: aws-ec2-pub-ip
          path: ./ansible

      - name: Setup SSH
        run: |
          echo "${{ secrets.MYAWSKEY_PRIVATE }}" > private_key.pem
          chmod 600 private_key.pem

      - name: install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook \
            -u ubuntu \
            --private-key private_key.pem \
            playbook.yml
